"""Clean raw claims into data/clean/claims.parquet and log every check in DATA_QUALITY.md."""
import os

import duckdb

con = duckdb.connect()
con.execute("CREATE TABLE raw_claims AS SELECT * FROM read_csv('data/raw/claims_main.csv', types={'place_of_service_code': 'VARCHAR', 'cpt_code': 'VARCHAR'})")
con.execute("CREATE TABLE raw_labels AS SELECT * FROM read_csv('data/raw/denial_labels.csv')")
one = lambda q: con.sql(q).fetchone()[0]

# (check, count, decision) -- every count comes from a query on the raw tables
checks = [
    ("Raw claim rows", one("SELECT count(*) FROM raw_claims"), "Starting point"),
    ("Duplicate claim_id rows", one("SELECT count(*) - count(DISTINCT claim_id) FROM raw_claims"), "Dropped, first kept"),
    ("Claim amount <= 0", one("SELECT count(*) FROM raw_claims WHERE claim_amount_usd <= 0"), "Dropped"),
    ("Date outside 2021-01-01..2024-06-30", one("SELECT count(*) FROM raw_claims WHERE claim_submission_date NOT BETWEEN '2021-01-01' AND '2024-06-30'"), "Dropped"),
    ("Null claim_id, outcome, payer, CPT or amount", one("SELECT count(*) FROM raw_claims WHERE claim_id IS NULL OR outcome IS NULL OR payer_type IS NULL OR cpt_code IS NULL OR claim_amount_usd IS NULL"), "None found; would be dropped"),
    ("Denial label rows / label rows with no matching claim", f"{one('SELECT count(*) FROM raw_labels')} / {one('SELECT count(*) FROM raw_labels WHERE claim_id NOT IN (SELECT claim_id FROM raw_claims)')}", "Labels joined 1:1 onto denied claims"),
    ("Duplicate claim_id in denial labels", one("SELECT count(*) - count(DISTINCT claim_id) FROM raw_labels"), "None found, so the label join cannot add rows"),
    ("Denied claims with no denial label", one("SELECT count(*) FROM raw_claims WHERE outcome = 'denied' AND claim_id NOT IN (SELECT claim_id FROM raw_labels)"), "None found"),
    ("Denial category present on a non-denied claim", one("SELECT count(*) FROM raw_claims WHERE denial_category IS NOT NULL AND outcome <> 'denied'"), "None found: denial fields are consistent with outcome"),
    ("Partial-pay claims", one("SELECT count(*) FROM raw_claims WHERE outcome = 'partial_pay'"), "Not counted as denials (paid in part, no denial code)"),
    ("Pending claims", one("SELECT count(*) FROM raw_claims WHERE outcome = 'pending'"), "Kept, but excluded from denial-rate denominators"),
    ("prior_auth_obtained blank (auth not required)", one("SELECT count(*) FROM raw_claims WHERE prior_auth_obtained IS NULL AND NOT prior_auth_required"), "Kept as blank: not applicable"),
    ("prior_auth_obtained blank (auth required)", one("SELECT count(*) FROM raw_claims WHERE prior_auth_obtained IS NULL AND prior_auth_required"), "Treated as not obtained"),
    ("Claims in 2024 (Jan-Jun only)", one("SELECT count(*) FROM raw_claims WHERE claim_year = 2024"), "Kept; 2024 is a half year, so trends use quarters, not years"),
    ("Billed amount above p99 ($" + f"{one('SELECT quantile_cont(claim_amount_usd, 0.99) FROM raw_claims'):,.0f})", one("SELECT count(*) FROM raw_claims WHERE claim_amount_usd > (SELECT quantile_cont(claim_amount_usd, 0.99) FROM raw_claims)"), "Kept: real high-cost claims, so dollar totals are skewed toward a few procedures"),
    ("Columns with a single value (dataset_version, synthetic_flag, generation_date)", sum(one(f"SELECT count(DISTINCT {c}) = 1 FROM raw_claims") for c in ["dataset_version", "synthetic_flag", "generation_date"]), "Dropped; synthetic_flag is TRUE on every row"),
]
con.execute(open("sql/00_clean.sql").read())
kept = one("SELECT count(*) FROM claims")
checks.append(("Final clean rows", kept, "One row per claim"))
os.makedirs("data/clean", exist_ok=True)
con.execute("COPY claims TO 'data/clean/claims.parquet' (FORMAT parquet)")

with open("DATA_QUALITY.md", "w", encoding="utf-8") as f:
    f.write("# Data quality log\n\nGenerated by `clean.py`; every count comes from a query, not typed by hand.\n\n"
            "| Check | Rows | Decision |\n|---|---|---|\n")
    f.writelines(f"| {c} | {n:,} | {d} |\n" if isinstance(n, int) else f"| {c} | {n} | {d} |\n" for c, n, d in checks)
print(f"raw {checks[0][1]} = kept {kept} + dropped {checks[0][1] - kept}")
